version: '3.8'
services:
  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: interview-assistant-asr
    ports:
      - "9001:9000"
    environment:
      - ASR_MODEL=small
      - ASR_ENGINE=openai_whisper
    volumes:
      - ./whisper-models:/root/.cache/whisper
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

